# lib/familia/features/relationships/participation/staged_operations.rb
#
# frozen_string_literal: true

require_relative 'through_model_operations'

module Familia
  module Features
    module Relationships
      module Participation
        # StagedOperations provides lifecycle management for staged (deferred) relationships.
        #
        # Staged relationships enable invitation workflows where a through model must exist
        # before the participant does. The staging set holds through model objids until
        # the relationship is activated.
        #
        # Key characteristics:
        # - UUID identifier: Staged models use UUID keys (not composite keys)
        # - Deferred activation: Through model exists before participant
        # - Clean handoff: Activation creates composite-keyed model, destroys UUID-keyed model
        # - Lazy cleanup: Ghost entries (deleted models still in staging set) are cleaned on access
        #
        # Lifecycle:
        #   stage    → UUID-keyed through model + ZADD staging set
        #   activate → composite-keyed through model + ZADD active + SADD participations + cleanup
        #   unstage  → ZREM staging + destroy through model
        #
        # Example:
        #   class Membership < Familia::Horreum
        #     feature :object_identifier
        #     field :organization_objid
        #     field :customer_objid
        #     field :email
        #     field :role
        #     field :status
        #   end
        #
        #   class Customer < Familia::Horreum
        #     participates_in Organization, :members,
        #       through: Membership,
        #       staged: :pending_members
        #   end
        #
        #   # Stage (invitation sent)
        #   membership = org.stage_members_instance(through_attrs: { email: 'invite@example.com' })
        #
        #   # Activate (invitation accepted)
        #   activated = org.activate_members_instance(membership, customer, through_attrs: { status: 'active' })
        #
        module StagedOperations
          module_function

          # Stage a new through model for deferred activation.
          #
          # Creates a through model with a UUID key (not composite) and sets only the
          # target foreign key. The participant foreign key remains nil until activation.
          #
          # The UUID comes from the through model's `feature :object_identifier` init hook.
          # This is the key difference from ThroughModelOperations.find_or_create, which
          # uses build_key to create a composite key from target and participant.
          #
          # @param through_class [Class] The through model class (must have feature :object_identifier)
          # @param target [Object] The target instance (e.g., organization)
          # @param attrs [Hash] Attributes to set on the through model
          # @return [Object] The created through model instance with UUID objid
          #
          def stage(through_class:, target:, attrs: {})
            # Create through model - UUID is auto-generated by object_identifier feature's init hook
            # No objid parameter passed = feature generates UUID (not composite key like find_or_create)
            inst = through_class.new

            # Set target foreign key only (participant is nil during staging)
            target_field = "#{target.class.config_name}_objid"
            inst.send("#{target_field}=", target.objid) if inst.respond_to?("#{target_field}=")

            # Set custom attributes (validated against field schema)
            safe_attrs = ThroughModelOperations.validated_attrs(through_class, attrs)
            safe_attrs.each { |k, v| inst.send("#{k}=", v) }

            # Timestamps
            inst.created_at = Familia.now.to_f if inst.respond_to?(:created_at=)
            inst.updated_at = Familia.now.to_f if inst.respond_to?(:updated_at=)

            inst.save
            inst
          end

          # Activate a staged through model, completing the relationship.
          #
          # This operation:
          # 1. Creates a new composite-keyed through model via ThroughModelOperations
          # 2. Destroys the UUID-keyed staged model
          #
          # The caller is responsible for the sorted set operations (ZADD active,
          # SADD participations, ZREM staging) which happen in a transaction in
          # the target method builder.
          #
          # @param through_class [Class] The through model class
          # @param staged_model [Object] The staged through model to activate
          # @param target [Object] The target instance
          # @param participant [Object] The participant instance (now exists)
          # @param attrs [Hash] Attributes for the activated through model
          # @return [Object] The new composite-keyed through model
          #
          def activate(through_class:, staged_model:, target:, participant:, attrs: {})
            # Create composite-keyed through model via existing machinery
            activated_model = ThroughModelOperations.find_or_create(
              through_class: through_class,
              target: target,
              participant: participant,
              attrs: attrs
            )

            # Destroy the UUID-keyed staged model
            staged_model.destroy!

            activated_model
          end

          # Unstage a through model, removing it from the staging set.
          #
          # Used when an invitation is revoked before acceptance.
          # The caller handles ZREM from staging set.
          #
          # @param staged_model [Object] The staged through model to remove
          # @return [void]
          #
          def unstage(staged_model:)
            staged_model.destroy!
          end

          # Clean up a stale staging set entry.
          #
          # Called when a staged model no longer exists (e.g., TTL expiration, manual deletion)
          # but its objid is still in the staging set. This implements lazy cleanup similar
          # to how Familia handles ghost entries in the `instances` sorted set.
          #
          # @param staging_collection [Familia::SortedSet] The staging collection
          # @param staged_objid [String] The objid to clean up
          # @return [Boolean] true if entry was removed, false if not found
          #
          def cleanup_stale_staged_entry(staging_collection:, staged_objid:)
            removed = staging_collection.remove(staged_objid)
            Familia.debug "[StagedOperations] Cleaned up stale staging entry: #{staged_objid}" if removed
            removed
          end

          # Load a staged model with lazy cleanup.
          #
          # Attempts to load the through model by objid. If the model doesn't exist
          # (ghost entry), cleans up the staging set entry and returns nil.
          #
          # @param through_class [Class] The through model class
          # @param staged_objid [String] The objid to load
          # @param staging_collection [Familia::SortedSet, nil] Optional staging collection for cleanup
          # @return [Object, nil] The loaded model or nil if not found
          #
          def load_staged(through_class:, staged_objid:, staging_collection: nil)
            model = through_class.load(staged_objid)

            # Check if model actually exists (not just loaded with empty data)
            if model.nil? || !model.exists?
              # Clean up ghost entry if staging collection provided
              cleanup_stale_staged_entry(
                staging_collection: staging_collection,
                staged_objid: staged_objid
              ) if staging_collection

              return nil
            end

            model
          end
        end
      end
    end
  end
end
