# .rubocop.yml

##
# This is the RuboCop configuration file.
# It contains the rules and settings for the RuboCop linter.
#
# Enable/disable the cops individually. For more information,
# refer to the RuboCop documentation:
# https://docs.rubocop.org/rubocop/cops.html
#
# Running `rubocop --regenerate-todo` will update the todo file
# with the latest state of the onion (using the same options
# as those documented at the top of the todo file). This is
# useful for a gradual migration of the codebase.
#
# How to resolve "RuboCop version incompatibility found":
#  `rubocop --stop-server`
#

plugins:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  UseCache: true
  MaxFilesInCache: 100
  TargetRubyVersion: 3.4
  Exclude:
    - "rspec/**/*.rb"
    - "tmp/**/*.rb"
    - "try/**/*.rb"

#
# Trailing commas
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInBlockArgs:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

# Format with consistent indentation levels rather than vertical dot alignment.
Layout/MultilineMethodCallIndentation:
  Enabled: false
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/IndentationWidth:
  Width: 2

Layout/ArgumentAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading # or 'trailing'

Lint/Void:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/ClassLength:
  Enabled: true
  Max: 350

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 50
  CountAsOne: ["method_call"]

Metrics/ModuleLength:
  Enabled: true
  Max: 350
  CountAsOne: ["method_call"]

Metrics/ParameterLists:
  Enabled: true
  Max: 6

Performance/Size:
  Enabled: true
  Exclude:
  #   - lib/example.rb

Style/NegatedIfElseCondition:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Naming/MemoizedInstanceVariableName:
  Enabled: false

ThreadSafety/ClassAndModuleAttributes:
  Enabled: false

ThreadSafety/ClassInstanceVariable:
  Enabled: false

ThreadSafety/MutableClassInstanceVariable:
  Enabled: false
