name: Build and Publish YARD Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual documentation build'
        required: false
        default: 'Manual documentation update'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_docs:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build YARD documentation
        run: |
          bundle exec yard doc \
            --output-dir ./doc \
            --readme README.md \
            --files 'docs/guides/*.md,docs/migration/*.md,examples/*.rb,CHANGELOG.md' \
            --title "Familia Documentation"
          # Ensure doc directory exists and create .nojekyll file to prevent GitHub Pages Jekyll processing
          mkdir -p ./doc
          touch ./doc/.nojekyll

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build_docs

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
